{% set version = "1.56.0" %}
{% set year = "2021" %}
{% set month = "08" %}
{% set day = "16" %}

package:
  name: rust-split
  version: {{ version }}.dev{{ year }}{{ month }}{{ day }}


source:
  url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-nightly-x86_64-unknown-linux-gnu.tar.gz  # [linux and x86_64]
  url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-nightly-aarch64-unknown-linux-gnu.tar.gz  # [aarch64]
  url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-nightly-powerpc64le-unknown-linux-gnu.tar.gz  # [ppc64le]
  url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-nightly-x86_64-apple-darwin.tar.gz  # [osx and x86_64]
  url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-nightly-aarch64-apple-darwin.tar.gz  # [osx and arm64]
  url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-nightly-x86_64-pc-windows-msvc.tar.gz  # [win64]
  sha256: 29e337c998149cb7f506ef3ebbbdd36a89885589cd27c54f2f31a4a844c857fc  # [win64]
  sha256: b3607d66c68b2551dca122246a1bcbd47ec08dee5c46d1a60d41f356a1355b48  # [osx and x86_64]
  sha256: db3e2bff208bd596a59ccc5dc86d0aff2051fd671b804c06f5973994374a021f  # [linux and x86_64]
  sha256: 9f2f30f915ddac30054e587df3bb39b997c3857f2dd4547c60b5271a713bf257  # [linux and aarch64]
  sha256: fb01bc7fb19d34b2a0ba1a26f8df80e2dc0f07e8d2d77d409f543ca207f39497  # [linux and ppc64le]
  sha256: 6c662e8e441051ae5ddd186756457448ddf49a263382d677234bb8c273826da3  # [osx and arm64]
  patches:
    - 0001-gh-106-install.sh-Perfomance-Use-more-shell-builtins.diff

build:
  number: 1

requirements:
  build:
    - posix  # [win]
  host:

outputs:
  - name: rust-std-{{ rust_arch }}
    build:
      noarch: generic
      binary_relocation: false
      merge_build_host: false
    requirements:
      build:
        - posix  # [win]
      host:
      run:
    script: install-rust-std.sh  # [unix]
    script: install-rust-std.bat  # [win]
    test:
      commands:
        - test -d $PREFIX/lib/rustlib   # [unix]
        - if not exist %LIBRARY_PREFIX%/lib/rustlib exit 1  # [win]
        - echo {{ rust_arch }}

  - name: rust
    script: install-rust.sh  # [unix]
    script: install-rust.bat  # [win]
    build:
      # the distributed binaries are already relocatable
      binary_relocation: false
    run_exports:
      strong_constrains:
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
    requirements:
      build:
        - posix  # [win]
      host:
        - {{ pin_subpackage("rust-std-" ~ rust_arch, exact=True) }}
        - {{ compiler('c') }}  # [linux] -- rustc needs a toolchain to link executables
      run:
        - {{ pin_subpackage("rust-std-" ~ rust_arch, exact=True) }}
        - gcc_impl_{{ target_platform }}  # [linux]
    test:
      requires:
        - posix  # [win]
      commands:
        - set "REQUESTS_CA_BUNDLE="  # [win]
        - set "SSL_CERT_FILE="       # [win]
        - unset REQUESTS_CA_BUNDLE  # [unix]
        - unset SSL_CERT_FILE       # [unix]
        - rustc --version
        - rustc --version 1>version.txt 2>&1
        # the day can be off-by-one
        - cat version.txt | grep "rustc {{ version.replace('.', '\\.') }}-nightly \(.* {{ year }}-{{ month }}-.*\)"
        - rustc --help
        - rustdoc --help
        - cargo --help
        - cargo install --force xsv
        - echo {{ rust_arch }}

about:
  home: https://www.rust-lang.org
  license: MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
  summary: |
    Rust is a systems programming language that runs blazingly fast, prevents segfaults, and guarantees thread safety.
    This package provides the compiler (rustc) and the documentation utilities rustdoc.
  dev_url: https://doc.rust-lang.org/std/
  doc_url: https://www.rust-lang.org/en-US/documentation.html

extra:
  recipe-maintainers:
    - johanneskoester
    - abhi18av
    - pkgw
    - dlaehnemann
    - isuruf
