ver="${1:-$(date +%Y-%m-%d)}"
echo "  - url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-nightly-x86_64-unknown-linux-gnu.tar.gz  # [linux and x86_64]"
echo "    sha256: $(wget -q -O - https://static.rust-lang.org/dist/$ver/rust-nightly-x86_64-unknown-linux-gnu.tar.gz.sha256 | cut -d " " -f1)  # [linux and x86_64]"
echo "  - url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-nightly-aarch64-unknown-linux-gnu.tar.gz  # [aarch64]"
echo "    sha256: $(wget -q -O - https://static.rust-lang.org/dist/$ver/rust-nightly-aarch64-unknown-linux-gnu.tar.gz.sha256 | cut -d " " -f1)  # [aarch64]"
echo "  - url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-nightly-powerpc64le-unknown-linux-gnu.tar.gz  # [ppc64le]"
echo "    sha256: $(wget -q -O - https://static.rust-lang.org/dist/$ver/rust-nightly-powerpc64le-unknown-linux-gnu.tar.gz.sha256 | cut -d " " -f1)  # [ppc64le]"
echo "  - url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-nightly-x86_64-apple-darwin.tar.gz  # [osx and x86_64]"
echo "    sha256: $(wget -q -O - https://static.rust-lang.org/dist/$ver/rust-nightly-x86_64-apple-darwin.tar.gz.sha256 | cut -d " " -f1)  # [osx and x86_64]"
echo "  - url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-nightly-aarch64-apple-darwin.tar.gz  # [osx and arm64]"
echo "    sha256: $(wget -q -O - https://static.rust-lang.org/dist/$ver/rust-nightly-aarch64-apple-darwin.tar.gz.sha256 | cut -d " " -f1)  # [osx and arm64]"
echo "  - url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-nightly-x86_64-pc-windows-msvc.tar.gz  # [win64]"
echo "    sha256: $(wget -q -O - https://static.rust-lang.org/dist/$ver/rust-nightly-x86_64-pc-windows-msvc.tar.gz.sha256 | cut -d " " -f1)  # [win64]"
echo "  - url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-nightly-aarch64-pc-windows-msvc.tar.gz  # [win and arm64]"
echo "    sha256: $(wget -q -O - https://static.rust-lang.org/dist/$ver/rust-nightly-aarch64-pc-windows-msvc.tar.gz.sha256 | cut -d " " -f1)  # [win and arm64]"
echo "    patches:"
echo "      - 0001-gh-106-install.sh-Perfomance-Use-more-shell-builtins.patch"
echo "  # End of block of primary source files."
echo "  - url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-src-nightly.tar.gz"
echo "    sha256: $(wget -q -O - https://static.rust-lang.org/dist/$ver/rust-src-nightly.tar.gz.sha256 | cut -d " " -f1)"
echo "    folder: rust-src"
echo "  - url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-std-nightly-aarch64-apple-ios.tar.gz  # [(linux or win) and x86_64]"
echo "    sha256: $(wget -q -O - https://static.rust-lang.org/dist/$ver/rust-std-nightly-aarch64-apple-ios.tar.gz.sha256 | cut -d " " -f1)  # [(linux or win) and x86_64]"
echo "    folder: rust-std  # [(linux or win) and x86_64]"
echo "  - url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-std-nightly-x86_64-apple-ios.tar.gz  # [(linux or win) and x86_64]"
echo "    sha256: $(wget -q -O - https://static.rust-lang.org/dist/$ver/rust-std-nightly-x86_64-apple-ios.tar.gz.sha256 | cut -d " " -f1)  # [(linux or win) and x86_64]"
echo "    folder: rust-std  # [(linux or win) and x86_64]"
echo "  - url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-std-nightly-aarch64-apple-ios-sim.tar.gz  # [(linux or win) and x86_64]"
echo "    sha256: $(wget -q -O - https://static.rust-lang.org/dist/$ver/rust-std-nightly-aarch64-apple-ios-sim.tar.gz.sha256 | cut -d " " -f1)  # [(linux or win) and x86_64]"
echo "    folder: rust-std  # [(linux or win) and x86_64]"
echo "  - url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-std-nightly-aarch64-linux-android.tar.gz  # [(linux or win) and x86_64]"
echo "    sha256: $(wget -q -O - https://static.rust-lang.org/dist/$ver/rust-std-nightly-aarch64-linux-android.tar.gz.sha256 | cut -d " " -f1)  # [(linux or win) and x86_64]"
echo "    folder: rust-std  # [(linux or win) and x86_64]"
echo "  - url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-std-nightly-arm-linux-androideabi.tar.gz  # [(linux or win) and x86_64]"
echo "    sha256: $(wget -q -O - https://static.rust-lang.org/dist/$ver/rust-std-nightly-arm-linux-androideabi.tar.gz.sha256 | cut -d " " -f1)  # [(linux or win) and x86_64]"
echo "    folder: rust-std  # [(linux or win) and x86_64]"
echo "  - url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-std-nightly-armv7-linux-androideabi.tar.gz  # [(linux or win) and x86_64]"
echo "    sha256: $(wget -q -O - https://static.rust-lang.org/dist/$ver/rust-std-nightly-armv7-linux-androideabi.tar.gz.sha256 | cut -d " " -f1)  # [(linux or win) and x86_64]"
echo "    folder: rust-std  # [(linux or win) and x86_64]"
echo "  - url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-std-nightly-i686-linux-android.tar.gz  # [(linux or win) and x86_64]"
echo "    sha256: $(wget -q -O - https://static.rust-lang.org/dist/$ver/rust-std-nightly-i686-linux-android.tar.gz.sha256 | cut -d " " -f1)  # [(linux or win) and x86_64]"
echo "    folder: rust-std  # [(linux or win) and x86_64]"
echo "  - url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-std-nightly-x86_64-linux-android.tar.gz  # [(linux or win) and x86_64]"
echo "    sha256: $(wget -q -O - https://static.rust-lang.org/dist/$ver/rust-std-nightly-x86_64-linux-android.tar.gz.sha256 | cut -d " " -f1)  # [(linux or win) and x86_64]"
echo "    folder: rust-std  # [(linux or win) and x86_64]"
echo "  - url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-std-nightly-wasm32-unknown-unknown.tar.gz  # [(linux or win) and x86_64]"
echo "    sha256: $(wget -q -O - https://static.rust-lang.org/dist/$ver/rust-std-nightly-wasm32-unknown-unknown.tar.gz.sha256 | cut -d " " -f1)  # [(linux or win) and x86_64]"
echo "    folder: rust-std  # [(linux or win) and x86_64]"
echo "  - url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-std-nightly-x86_64-pc-windows-msvc.tar.gz  # [(linux or win) and x86_64]"
echo "    sha256: $(wget -q -O - https://static.rust-lang.org/dist/$ver/rust-std-nightly-x86_64-pc-windows-msvc.tar.gz.sha256 | cut -d " " -f1)  # [(linux or win) and x86_64]"
echo "    folder: rust-std  # [(linux or win) and x86_64]"
echo "  - url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-std-nightly-wasm32-unknown-emscripten.tar.gz  # [(linux or win) and x86_64]"
echo "    sha256: $(wget -q -O - https://static.rust-lang.org/dist/$ver/rust-std-nightly-wasm32-unknown-emscripten.tar.gz.sha256 | cut -d " " -f1)  # [(linux or win) and x86_64]"
echo "    folder: rust-std  # [(linux or win) and x86_64]"
echo "  - url: https://static.rust-lang.org/dist/{{ year }}-{{ month }}-{{ day }}/rust-std-nightly-aarch64-pc-windows-msvc.tar.xz  # [(linux or win) and x86_64]"
echo "    sha256: $(wget -q -O - https://static.rust-lang.org/dist/$ver/rust-std-nightly-aarch64-pc-windows-msvc.tar.xz.sha256 | cut -d " " -f1)  # [(linux or win) and x86_64]"
echo "    folder: rust-std  # [(linux or win) and x86_64]"
