ver="${1:-$(date +%Y-%m-%d)}"
echo "  sha256: $(wget -q -O - https://static.rust-lang.org/dist/$ver/rust-nightly-x86_64-pc-windows-msvc.tar.gz.sha256 | cut -d " " -f1)  # [win64]"
echo "  sha256: $(wget -q -O - https://static.rust-lang.org/dist/$ver/rust-nightly-x86_64-apple-darwin.tar.gz.sha256 | cut -d " " -f1)  # [osx and x86_64]"
echo "  sha256: $(wget -q -O - https://static.rust-lang.org/dist/$ver/rust-nightly-x86_64-unknown-linux-gnu.tar.gz.sha256 | cut -d " " -f1)  # [linux and x86_64]"
echo "  sha256: $(wget -q -O - https://static.rust-lang.org/dist/$ver/rust-nightly-aarch64-unknown-linux-gnu.tar.gz.sha256 | cut -d " " -f1)  # [linux and aarch64]"
echo "  sha256: $(wget -q -O - https://static.rust-lang.org/dist/$ver/rust-nightly-powerpc64le-unknown-linux-gnu.tar.gz.sha256 | cut -d " " -f1)  # [linux and ppc64le]"
echo "  sha256: $(wget -q -O - https://static.rust-lang.org/dist/$ver/rust-nightly-aarch64-apple-darwin.tar.gz.sha256 | cut -d " " -f1)  # [osx and arm64]"
