build_platform: {osx_arm64: osx_64}
conda_forge_output_validation: true
provider: {linux_aarch64: azure, linux_ppc64le: azure}
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
test: native_and_emulated
# See https://github.com/conda-forge/rust-feedstock/pull/210#issuecomment-2352764197
remote_ci_setup:
  - conda-forge-ci-setup=4
  - conda-build>=24.1
  - conda-libmamba-solver=24.1.0
