build_platform: {osx_arm64: osx_64}
conda_forge_output_validation: true
provider: {linux_aarch64: azure, linux_ppc64le: azure}
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
test: native_and_emulated
remote_ci_setup:
  conda=24.3.0
  conda-build=24.7.1
  conda-forge-ci-setup=4
  python=3.10
